// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdkhrbzbpsfmdagxctrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBka2hyYnpicHNmbWRhZ3hjdHJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTk3NTEsImV4cCI6MjA3MTY5NTc1MX0.2AS-XfhIKJZw01Rct7Z2UEfPPM4JspPk0jnzlQ4OrzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});